"""empty message

Revision ID: 3739c391d95f
Revises: d8b8df589ed3
Create Date: 2023-12-01 12:56:59.426840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3739c391d95f'
down_revision = 'd8b8df589ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shortDescription', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('image1', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(length=2000), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('image2')
        batch_op.drop_column('image1')
        batch_op.drop_column('shortDescription')

    # ### end Alembic commands ###
